version: '3.1'
services:
    db:
        image: postgres
        hostname: db
        restart: always
        ports:
        - "5434:5432"
        environment:
        - POSTGRES_PASSWORD=1234
        - POSTGRES_DB=university
        volumes:
        - db_data_volume:/var/lib/postgresql/data
        - ./db.sql:/docker-entrypoint-initdb.d/db.sql
volumes:
    db_data_volume:
